### ISSUE TITLE
Is it possible to generate the landmark from the VG output?

### ISSUE THREAD

**Issue by snowzhangy** [lelechen63/ATVGnet#13]
Hi:
  I'm testing to get the landmarks from the output facial images. Since the VG output images are cropped, the landmarks not so stable from dlib.  Is that possible to generate the landmarks directly from VG net? Since we already have a landmark input for the vg net.
thanks

**Comment by lelechen63** [comment]
Hi,
Yes, you can save the output from the discriminator of VGnet. The discriminator (GL_Discriminator) actually regresses the landmark from the input image. You can simply convert the output into integers and visualize it. However, this is not a standard library to regress accurate landmark. So, if you want to evaluate the quality of output images from vgnet, you should use dlib. Or you can consider this work (https://github.com/YadiraF/PRNet) to regress landmark from the image.

**Comment by snowzhangy** [comment]
> Hi,
> Yes, you can save the output from the discriminator of VGnet. The discriminator (GL_Discriminator) actually regresses the landmark from the input image. You can simply convert the output into integers and visualize it. However, this is not a standard library to regress accurate landmark. So, if you want to evaluate the quality of output images from vgnet, you should use dlib. Or you can consider this work (https://github.com/YadiraF/PRNet) to regress landmark from the image.

thanks Lelechen for the suggestion!
I will give a try both ways.
