### ISSUE TITLE
The use of mean_shape_norm.npy & S.npy & S_3d.npy?

### ISSUE THREAD

**Issue by Songluchuan** [lelechen63/ATVGnet#14]
Hello, 
I learned about ATVGNet at CVPR2019 site.And this is a very interesting work！
But when I read code after that,some place made me confuse.
1.What is the  use of mean_shape_norm.npy & S.npy & S_3d.npy, I know it try to normazile landmark,but What is the individual function of the parts(mean_shape_norm.npy & S.npy & S_3d.npy)? Knowing this might give me a better understanding of the code.

2.How to get mean_shape_norm.npy & S.npy & S_3d.npy?

look forward to you reply

**Comment by lelechen63** [comment]
Hi there, I extract those from LRW dataset. Unfortunately, I lost the code for this part ... If I remember it correctly,  mean_shape_nor.npy is the landmark extracted from a standard front image (https://www.quora.com/Is-there-such-a-thing-as-an-average-face). The S.npy and S_3s.npy is the mean landmark shape extracted from LRW 2D landmark and LRW 3D landmark.  Besides normalizing the landmark value, the function can also remove identity information partially. However, I did more experiments recently and found this part can be ignored. You can simply normalize the landmarks to 0~1 without this complexes step to construct your own dataset.
Hope this can help you.

**Comment by Songluchuan** [comment]
thank you !
You reply help me a lot !
So that is why I normalize different face,but get same landmark.
Thanks you again !

**Comment by Owen-Fish** [comment]
@lelechen63 "You can simply normalize the landmarks to 0~1 without this complexes step to construct your own dataset." Does this means there is no need to identity( and head rotation) removal of facial landmarks?
