### ISSUE TITLE
Question about PCA preprocessing

### ISSUE THREAD

**Issue by pcgreat** [lelechen63/ATVGnet#16]
In demo.py, you multiply the example_landmark by 5 before applying PCA,
```
example_landmark = example_landmark * 5.0
example_landmark = example_landmark - mean.expand_as(example_landmark)
example_landmark = torch.mm(example_landmark, pca)
```
And for fake_landmarks, you multiply 2 times 1.1~1.5 before applying PCA
```
fake_lmark[:, 1:6] *= 2 * torch.FloatTensor(np.array([1.1, 1.2, 1.3, 1.4, 1.5])).cuda()
fake_lmark = torch.mm(fake_lmark, pca.t())
fake_lmark = fake_lmark + mean.expand_as(fake_lmark)
```
so (1) do you apply different scaling parameters for example_landmark and fake_landmarks?
(2) how are those scaling parameters (5 vs 2.2~3.0) being selected?

**Comment by lelechen63** [comment]
> In demo.py, you multiply the example_landmark by 5 before applying PCA,
> 
> ```
> example_landmark = example_landmark * 5.0
> example_landmark = example_landmark - mean.expand_as(example_landmark)
> example_landmark = torch.mm(example_landmark, pca)
> ```
> 
> And for fake_landmarks, you multiply 2 times 1.1~1.5 before applying PCA
> 
> ```
> fake_lmark[:, 1:6] *= 2 * torch.FloatTensor(np.array([1.1, 1.2, 1.3, 1.4, 1.5])).cuda()
> fake_lmark = torch.mm(fake_lmark, pca.t())
> fake_lmark = fake_lmark + mean.expand_as(fake_lmark)
> ```
> 
> so (1) do you apply different scaling parameters for example_landmark and fake_landmarks?
> (2) how are those scaling parameters (5 vs 2.2~3.0) being selected?

The landmark after normalization is [-0.2, 0.2]. I multiply with 5 to make it between [-1, 1]. The PCA files were calculated based on npy after multiply with 5. So here we did  example_landmark = example_landmark * 5.0.  The fake_lmark is the /omega is the paper. We manually choose \omega.

**Comment by pcgreat** [comment]
That

**Comment by pcgreat** [comment]
That makes perfect sense. Thanks for the explanation!
