### ISSUE TITLE
Segmentation fault when running program

### ISSUE THREAD

**Issue by HallidayReadyOne** [lelechen63/ATVGnet#18]
Hi @lelechen63.
When I ran the demo, I encountered Segmentation fault.
After debugging, it was found that torch and Dlib should be the cause.
Can you share the version of Dlib?

**Comment by lelechen63** [comment]
Currently, I am using diib 19.17. You should install dlib using pip rather than conda.

**Comment by HallidayReadyOne** [comment]
Thank you for the reply.
I tried dlib 19.17(installed by pip), torch(0.4.1,cuda9.0), trochvision(0.2.1).
But it doesn't work.
Do you have any idea?

**Comment by lelechen63** [comment]
> Thank you for the reply.
> I tried dlib 19.17(installed by pip), torch(0.4.1,cuda9.0), trochvision(0.2.1).
> But it doesn't work.
> Do you have any idea?

Can you show me your error message?

**Comment by HallidayReadyOne** [comment]
The error message is only one line： segmentation fault. It is caused by import torch and dlib at the same time. But i dont know how to solve it.

**Comment by HallidayReadyOne** [comment]
Hi @lelechen63, I have tried to install torch by “conda install pytorch=0.4.1 torchvision cuda90 -c pytorch” and install dlib by “pip install dlib==19.17.0”.  But I got segmentation fault again. Could you please share the full env that you can run the demo.py (cudnn, cuda).

**Comment by HallidayReadyOne** [comment]
Hi @lelechen63, I have tried to install torch by “conda install pytorch=0.4.1 torchvision cuda90 -c pytorch” and install dlib by “pip install dlib==19.17.0”. But I got segmentation fault again(the error message is only one line). Could you please share the full env that you can run the demo.py (cudnn, cuda).

**Comment by lelechen63** [comment]
> Hi @lelechen63, I have tried to install torch by “conda install pytorch=0.4.1 torchvision cuda90 -c pytorch” and install dlib by “pip install dlib==19.17.0”. But I got segmentation fault again(the error message is only one line). Could you please share the full env that you can run the demo.py (cudnn, cuda).

I just test with it. It works for me. I just create a conda virtual environment with python 2.7. Then I install pytorch: conda install pytorch=0.4.1 cuda90 -c pytorch
install dlib: pip install dlib
install torchvision: pip install torchvision

And then I can generate images without any error message. Hope this can help you.

**Comment by HallidayReadyOne** [comment]
Thank you again, i will try this.

**Comment by tlatlbtle** [comment]
The same issue. Have you solved it?

**Comment by tlatlbtle** [comment]
I just solved this problem by using conda to install dlib instead of pip ( by command="pip install -r requirements.txt").
I installed dlib following this guidance: https://github.com/conda-forge/dlib-feedstock
```
conda config --add channels conda-forge
conda install dlib
```

**Comment by lelechen63** [comment]
> I just solved this problem by using conda to install dlib instead of pip ( by command="pip install -r requirements.txt").
> I installed dlib following this guidance: https://github.com/conda-forge/dlib-feedstock
> 
> ```
> conda config --add channels conda-forge
> conda install dlib
> ```

Thanks for sharing this!

**Comment by HallidayReadyOne** [comment]
Thank you @wjbKimberly. I solved it by @lelechen63‘s method.

**Comment by moment0517** [comment]
with centos 7, I solved it by degrading dlib to 19.4.0.
