### ISSUE TITLE
no requirements.txt and other issues

### ISSUE THREAD

**Issue by ghost** [lelechen63/ATVGnet#2]
there is no requirements.txt
also model.py has a bug
this lines should be 
model += [nn.Conv2d(ngf // 2, output_nc, kernel_size=7, padding=3)]
and 
model += [nn.Conv2d(ngf // 2, 1, kernel_size=7, padding=3)]
to avoid floating point error 
and with torch=0.4.1 there is a cuda issue
RuntimeError: CuDNN error: CUDNN_STATUS_SUCCESS
upgrading to 1.1.0 causes this issue
ImportError: cannot import name 'rnnFusedPointwise'

**Comment by lelechen63** [comment]
The requirement.txt is in code folder. Yes, it should be ngf//2 but all we usually set ngf = 64 or 128 so we will not have any problems. I am not sure about your cuDNN error. I have tested my code on different machines already. It should work

**Comment by ghost** [comment]
ok I was able to use a fork by https://github.com/snowzhangy/ATVGnet to run in python 3 without the cudnn error, also the result only shows mouth movement with no facial expressions movement
