### ISSUE TITLE
bigger?

### ISSUE THREAD

**Issue by gucasbrg** [lelechen63/ATVGnet#20]
1, use tf.warp, part of face cut off,can you provide landmark bigger?
2, the resolution of 128 * 128 is very small ,  enlarge?

**Comment by lelechen63** [comment]
> 1, use tf.warp, part of face cut off,can you provide landmark bigger?
> 2, the resolution of 128 * 128 is very small , enlarge?

If you want to use a larger region, you can adjust the crop_image function.
```

def crop_image(image_path):
    image = cv2.imread(image_path)
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    rects = detector(gray, 1)
    for (i, rect) in enumerate(rects):
        shape = predictor(gray, rect)
        shape = utils.shape_to_np(shape)
        (x, y, w, h) = utils.rect_to_bb(rect)
        center_x = x + int(0.5 * w)
        center_y = y + int(0.5 * h)
        r = int(0.64 * h)
        new_x = center_x - r
        new_y = center_y - r
        roi = image[new_y:new_y + 2 * r, new_x:new_x + 2 * r]
        roi = cv2.resize(roi, (163,163), interpolation = cv2.INTER_AREA)
        scale =  163. / (2 * r)
        shape = ((shape - np.array([new_x,new_y])) * scale)
        return roi, shape 
```


Here, r controls the crop region size. Once you have a new cropped image, then you can apply dlib or other landmark detectors on this cropped image. You will have a larger rgb region with the paired landmark. Unfortunately, this paper can only handle the default setting here.
