### ISSUE TITLE
Where is the network architecture?

### ISSUE THREAD

**Issue by AtaUllahB** [lelechen63/ATVGnet#21]
We are trying to deploy this project on an android application. In order to do so, we need to convert the pretrained pytorch model (atnet_lstm_18.pth and generator_23.pth) into tensorflow but it shows an error of 'state_dict'.
When i load the pre trained models, it only gives the weights but not the architecture.
Can you guide me where i can find the Model architecture?
And how to convert it to tensorflow?
![WhatsApp Image 2019-10-22 at 9 28 59 PM](https://user-images.githubusercontent.com/53036114/67308581-c6ccb900-f513-11e9-88c1-34b607f9183e.jpeg)

**Comment by AtaUllahB** [comment]
Can you please guide me how to do that?
im desparate. :(

![2019-10-22_2138](https://user-images.githubusercontent.com/53036114/67308911-6db15500-f514-11e9-8691-86bdd4974873.png)

**Comment by lelechen63** [comment]
> We are trying to deploy this project on an android application. In order to do so, we need to convert the pretrained pytorch model (atnet_lstm_18.pth and generator_23.pth) into tensorflow but it shows an error of 'state_dict'.
> When i load the pre trained models, it only gives the weights but not the architecture.
> Can you guide me where i can find the Model architecture?
> And how to convert it to tensorflow?
> ![WhatsApp Image 2019-10-22 at 9 28 59 PM](https://user-images.githubusercontent.com/53036114/67308581-c6ccb900-f513-11e9-88c1-34b607f9183e.jpeg)

The code is in model.py.
from model import AT_net and VG_net 


You need to check dem.py to see how to deploy the pretrained model. You need to use the code in demo.py to transfer the weight to the single GPU version and then you can load the weight to model. Make sure you are using pytorch 0.4.*.

**Comment by AtaUllahB** [comment]
Sorry sir. im new to GANs.
Can you please guide me some more?
Can you kindly explain what you mean by "transfer the weight to single GPU version".
Also the repo has two pretrained model. Will we need to convert both of them in order to convert it to tensorflow?

**Comment by TalkingPictures** [comment]
@lelechen63 Following your instructions i have made this code from demo.py.
Kindly guide me what is the next step?

> import torch
import torchvision
import argparse
from models import AT_net 
from models import VG_net
from collections import OrderedDict



def parse_args():
    parser = argparse.ArgumentParser()

    parser.add_argument("--batch_size",
                     type=int,
                     default=1)
    parser.add_argument("--cuda",
                     default=True)
    parser.add_argument("--lstm",
                     default=True)
    parser.add_argument("--vg_model",
                     type=str,
                     default="./model/generator_23.pth")
    parser.add_argument("--at_model",
                     type=str,
                     # default="/u/lchen63/lrw/model/audio2lmark_pca/audio2lmark_24.pth")
                     default="./model/atnet_lstm_18.pth")
    parser.add_argument( "--sample_dir",
                    type=str,
                    default="./results")
                    # default='/media/lele/DATA/lrw/data2/sample/lstm_gan')test
    parser.add_argument('-i','--in_file', type=str, default='./audio/speech.wav')
    parser.add_argument('-d','--data_path', type=str, default='./basics')
    parser.add_argument('-p','--person', type=str, default='./image/quaid.jpg')
    parser.add_argument('--device_ids', type=str, default='2')
    parser.add_argument('--num_thread', type=int, default=1)   
    return parser.parse_args()
config = parse_args()

def multi2single(model_path, id):
    checkpoint = torch.load(model_path)
    state_dict = checkpoint
    if id ==1:
        new_state_dict = OrderedDict()
        for k, v in state_dict.items():
            name = k[7:]
            new_state_dict[name] = v
        return new_state_dict
    else:
        return state_dict

#vg_model = "./model/generator_23.pth"
#at_model = "./model/generator_23.pth"
decoder = VG_net()
encoder = AT_net()

if config.cuda:
 encoder = encoder.cuda()
 decoder = decoder.cuda()
 state_dict2 = multi2single(config.vg_model, 1)
 decoder.load_state_dict(state_dict2)
 state_dict = multi2single(config.at_model, 1)
encoder.load_state_dict(state_dict)
encoder.eval()
decoder.eval()
test_file = config.in_file

**Comment by AtaUllahB** [comment]
@lelechen63 Following your instructions i have made this code from demo.py.
Kindly guide me what is the next step?

> import torch
> import torchvision
> import argparse
> from models import AT_net
> from models import VG_net
> from collections import OrderedDict
> 
> def parse_args():
> parser = argparse.ArgumentParser()
> 
> parser.add_argument("--batch_size",
>                  type=int,
>                  default=1)
> parser.add_argument("--cuda",
>                  default=True)
> parser.add_argument("--lstm",
>                  default=True)
> parser.add_argument("--vg_model",
>                  type=str,
>                  default="./model/generator_23.pth")
> parser.add_argument("--at_model",
>                  type=str,
>                  # default="/u/lchen63/lrw/model/audio2lmark_pca/audio2lmark_24.pth")
>                  default="./model/atnet_lstm_18.pth")
> parser.add_argument( "--sample_dir",
>                 type=str,
>                 default="./results")
>                 # default='/media/lele/DATA/lrw/data2/sample/lstm_gan')test
> parser.add_argument('-i','--in_file', type=str, default='./audio/speech.wav')
> parser.add_argument('-d','--data_path', type=str, default='./basics')
> parser.add_argument('-p','--person', type=str, default='./image/quaid.jpg')
> parser.add_argument('--device_ids', type=str, default='2')
> parser.add_argument('--num_thread', type=int, default=1)   
> return parser.parse_args()
> config = parse_args()
> 
> def multi2single(model_path, id):
> checkpoint = torch.load(model_path)
> state_dict = checkpoint
> if id ==1:
> new_state_dict = OrderedDict()
> for k, v in state_dict.items():
> name = k[7:]
> new_state_dict[name] = v
> return new_state_dict
> else:
> return state_dict
> 
> #vg_model = "./model/generator_23.pth"
> #at_model = "./model/generator_23.pth"
> decoder = VG_net()
> encoder = AT_net()
> 
> if config.cuda:
> encoder = encoder.cuda()
> decoder = decoder.cuda()
> state_dict2 = multi2single(config.vg_model, 1)
> decoder.load_state_dict(state_dict2)
> state_dict = multi2single(config.at_model, 1)
> encoder.load_state_dict(state_dict)
> encoder.eval()
> decoder.eval()
> test_file = config.in_file
