### ISSUE TITLE
State_dict

### ISSUE THREAD

**Issue by AtaUllahB** [lelechen63/ATVGnet#22]
Im trying to run this script.

> import torchvision
> import torch 
> from somefile import modelarchitecture
> model = modelarchitecture()
> model.load_state_dict(torch.load(???))
> model.eval()

Please guide me which values will be set for "model" and path inside torch.load?

**Comment by lelechen63** [comment]
> Im trying to run this script.
> 
> > import torchvision
> > import torch
> > from somefile import modelarchitecture
> > model = modelarchitecture()
> > model.load_state_dict(torch.load(???))
> > model.eval()
> 
> Please guide me which values will be set for "model" and path inside torch.load?
Check the code in dmeo.py
decoder = VG_net()
    encoder = AT_net()
    if config.cuda:
        encoder = encoder.cuda()
        decoder = decoder.cuda()
    state_dict2 = multi2single(config.vg_model, 1)
    decoder.load_state_dict(state_dict2)
    state_dict = multi2single(config.at_model, 1)
    encoder.load_state_dict(state_dict)

**Comment by AtaUllahB** [comment]
Im really sorry.
Im really confused.
Can you please be a little more specific?
Can you please explain the steps please?
