### ISSUE TITLE
Using Pre-trained Model on GRID dataset

### ISSUE THREAD

**Issue by avisekiit** [lelechen63/ATVGnet#25]
Dear Authors,
Thanks for sharing the code. I just wanted to know whether the pre-trained model which you have released can be used on GRID dataset or not? I am only interested to run your demo.py.
For example, I want to
1. give a frame from GRID dataset as a target frame
2. provide a .wav audio file from GRID

Do you think that should work. Or do I need to take any special care for GRID dataset demo.

**Comment by lelechen63** [comment]
> Dear Authors,
> Thanks for sharing the code. I just wanted to know whether the pre-trained model which you have released can be used on GRID dataset or not? I am only interested to run your demo.py.
> For example, I want to
> 
> 1. give a frame from GRID dataset as a target frame
> 2. provide a .wav audio file from GRID
> 
> Do you think that should work. Or do I need to take any special care for GRID dataset demo.

Hi there, 
Yes, you can use the model released to test on GRID directly, which we treate it as fear comparision since LRW training set is much larger than GRID training set.

**Comment by avisekiit** [comment]
Hello,
Thanks for the fast reply. Really appreciate your effort. So, just to confirm, if I want to test on GRID dataset 
1. I will select a frame of a subject for whom I want to generate
2. Feed a .wav file as a driving audio

I do not have to worry about any other pre/post processing steps for a fair comparison?
I will close the issue with this reply of yours.

Thanks,
Avisek

**Comment by lelechen63** [comment]
> Hello,
> Thanks for the fast reply. Really appreciate your effort. So, just to confirm, if I want to test on GRID dataset
> 
> 1. I will select a frame of a subject for whom I want to generate
> 2. Feed a .wav file as a driving audio
> 
> I do not have to worry about any other pre/post processing steps for a fair comparison?
> I will close the issue with this reply of yours.
> 
> Thanks,
> Avisek

Yep. You can feed any wav file and image to the network to test the performance.

**Comment by avisekiit** [comment]
Awesome. Thanks for the help. And congrats again for the wonderful work done in the paper.
