### ISSUE TITLE
Comparing on GRID dataset

### ISSUE THREAD

**Issue by avisekiit** [lelechen63/ATVGnet#26]
Dear Authors,
Thanks for the awesome release of the paper and code.

I was trying to compare our result with yours on the GRID dataset for the LMD metric. Can you please tell me that in the paper
1. Which subjects IDs of GRID did you use for testing.

2. How many keypoints did you use for each subject ? I usually use a dlib detector which gives me 68 keypoints.

3. Do you perform any normalization of the keypoints (after getting raw pixel coordinates using a dlib detector) to get rid of scale effects before calculating the difference on real and synthetic faces?

4. Lastly, when you report the SSIM and PSNR: do you calculate those metrics on the entire frame or just cropped out face regions.
I just wanted to make sure that we compare fairly with you. So, keenly looking forward to your kind reply.

Thanks,
Avisek Lahiri

**Comment by lelechen63** [comment]
> Dear Authors,
> Thanks for the awesome release of the paper and code.
> 
> I was trying to compare our result with yours on the GRID dataset for the LMD metric. Can you please tell me that in the paper
> 
>     1. Which subjects IDs of GRID did you use for testing.
> 
>     2. How many keypoints did you use for each subject ? I usually use a dlib detector which gives me 68 keypoints.
> 
>     3. Do you perform any normalization of the keypoints (after getting raw pixel coordinates using a dlib detector) to get rid of scale effects before calculating the difference on real and synthetic faces?
> 
>     4. Lastly, when you report the SSIM and PSNR: do you calculate those metrics on the entire frame or just cropped out face regions.
>        I just wanted to make sure that we compare fairly with you. So, keenly looking forward to your kind reply.
> 
> 
> Thanks,
> Avisek Lahiri

Hi there,

1. I am s29 as testing object.

2. I only use the mouth region landmark to compute LMD.
3. The evaluation code is released in the code folder.
4. We compute it on the output of ATVGnet. We also crop the ground truth using the same cropping protocol used to generate the input of ATVGnet

**Comment by avisekiit** [comment]
@lelechen63 
Thanks for the info. I also came across your ECCV'18 paper, "Lip Movements Generation at a Glance". Did you also use just s29 for ECCV paper testing also ?

Thanks,
Avisek
