### ISSUE TITLE
About audio2lmark_24.pth

### ISSUE THREAD

**Issue by sdulyq** [lelechen63/ATVGnet#40]
There is an error: No such file or directory: '../model/atnet/audio2lmark_24.pth' . And I cannot find this file in google drive

**Comment by lelechen63** [comment]
Please use this one https://drive.google.com/drive/folders/1WYhqKBFX6mLtdJ8sYVLdWUqp5FJDmphg

**Comment by sdulyq** [comment]
Sorry to trouble you but there is still no 'audio2lmark_24.pth' file in your interlinkage.

**Comment by lelechen63** [comment]
> Sorry to trouble you but there is still no 'audio2lmark_24.pth' file in your interlinkage.

Please use lstm_18.pth....
