### ISSUE TITLE
pickle file of dataset 

### ISSUE THREAD

**Issue by Mora-max** [lelechen63/ATVGnet#43]
hello,

would you share the code to generate the pickle file "new_16_full_gt_train.pkl",please?

**Comment by lelechen63** [comment]
> hello,
> 
> would you share the code to generate the pickle file "new_16_full_gt_train.pkl",please?

>>> a = open('new_16_full_gt_test.pkl', 'rb')
>>> train_data = pickle.load(a)
>>> print (train_data[0])
['NATIONAL/val/NATIONAL_00015/NATIONAL_00015_012.jpg', 12]
>>>
