### ISSUE TITLE
AT-net label相关问题

### ISSUE THREAD

**Issue by 821029883** [lelechen63/ATVGnet#44]
作者您好，感谢您出色的工作。
我有两个疑问比较疑惑
1.留意到您在AT-net中的dataset处理中，将mfcc特征向量堆叠为16个拼接在一起。
想问一下堆叠为16的依据是什么?(我们在deepspeech中也有留意到相似的做法)
"t_mfcc =mfcc[(r + ind - 3)*4: (r + ind + 4)*4, 1:]" 
这一步操作已经是选取了前后3帧共计280ms的特征向量，为什么还要将之拼接16次呢？
2."landmark  =lmark[r+1 : r + 17,:]" 正常来讲，我们的label不是以当前帧为中心，为什么这里选取了当前帧往后的16帧的landmark作为标签？
![图片](https://user-images.githubusercontent.com/52727204/121109473-39e88780-c83e-11eb-8e0c-59dcb7abfd7f.png)

期待您的解答，感激不尽！

**Comment by lelechen63** [comment]
> 作者您好，感谢您出色的工作。
> 我有两个疑问比较疑惑
> 1.留意到您在AT-net中的dataset处理中，将mfcc特征向量堆叠为16个拼接在一起。
> 想问一下堆叠为16的依据是什么?(我们在deepspeech中也有留意到相似的做法)
> "t_mfcc =mfcc[(r + ind - 3)*4: (r + ind + 4)*4, 1:]"
> 这一步操作已经是选取了前后3帧共计280ms的特征向量，为什么还要将之拼接16次呢？
> 2."landmark =lmark[r+1 : r + 17,:]" 正常来讲，我们的label不是以当前帧为中心，为什么这里选取了当前帧往后的16帧的landmark作为标签？
> ![图片](https://user-images.githubusercontent.com/52727204/121109473-39e88780-c83e-11eb-8e0c-59dcb7abfd7f.png)
> 
> 期待您的解答，感激不尽！

是的呢，因为每一个视频帧对应着4个mfcc帧。我们这里是以视频帧的前后7帧来代表中间的那一帧。每一个前后7帧，我们其实只对应一个中间的landamrk。这个for loop是16个lstm的cell input

**Comment by 821029883** [comment]
感谢您的解答，它对我帮助很大。
