### ISSUE TITLE
Error when installing opencv

### ISSUE THREAD

**Issue by aseyedia** [lelechen63/ATVGnet#46]
https://github.com/lelechen63/ATVGnet/blob/2d4d1b03df1c706c6575b942fd2a1585347c4aab/requirement.txt#L9

The above line in `requirements.txt` throws a pretty long error that is not worth reproducing in its entirety:

```
Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /home/arta/anaconda3/envs/py2/bin/python /home/arta/anaconda3/envs/py2/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmp88lNX5
       cwd: /tmp/pip-install-hhbrzT/opencv-python
```

I found [this website](https://remoted.tistory.com/418), that, when translated to English, describes a workaround whereby you specify a version of `opencv` that is compatible with Python 2.7:

`python -m pip install opencv-python==4.2.0.32`

I hope this helps.

**Comment by insung3511** [comment]
Could u try on pip3? I'm not sure but some version error could be.
And also I'm recommend use virtualenv to make virtual python develop environment.
