### ISSUE TITLE
is there some processed example data for reference?

### ISSUE THREAD

**Issue by lianDaniel** [lelechen63/ATVGnet#8]
I am trying to create data for this project. Is there some images or landmark*.npy can be downloaded? just as one processed landmark npy and image region~
thank you

**Comment by lianDaniel** [comment]
I find it, in the ./image

**Comment by lianDaniel** [comment]
One more question~, is there any difference for preprocessing with the paper "Generating Talking Face Landmarks from Speech",? I am troubling with it?

**Comment by lelechen63** [comment]
It is totally different since we need to keep identity information. The example preprocessing code can be found in demo.py.

**Comment by ghost** [comment]
hi, I found that there is some data processing code in the demo.py and it uses some data in the basics folder. What do these files mean and how to calculate them? (mean_shape_img.npy, mean_shape_norm.npy, S.npy)
thank you

**Comment by lelechen63** [comment]
Hi Ya,

Basically, those are used for normalizing the landmark shape. You can directly use it even if you want to work on your own dataset.


Best,
Lele
________________________________

**Comment by ghost** [comment]
I'll try. Thanks!




------------------ 原始邮件 ------------------
发件人: "Lele Chen"<notifications@github.com>;
发送时间: 2019年6月22日(星期六) 凌晨3:06
收件人: "lelechen63/ATVGnet"<ATVGnet@noreply.github.com>;
抄送: "519553493"<519553493@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [lelechen63/ATVGnet] is there some processed example data forreference? (#8)



Hi Ya,
 
 Basically, those are used for normalizing the landmark shape. You can directly use it even if you want to work on your own dataset.
 
 
 Best,
 Lele
 ________________________________

**Comment by lianDaniel** [comment]
hi, @lelechen63 ,  thank you for your response， but I have trouble in test the model in dataset. For example, LRW, as we know, there is dev set and val set. So I test the model in val set. What I do as below:
1. get the data by test_data_loder as train_data_loder, which can provide a batch of example mfcc, example lmark, mfcc and so on.
2. i get fake landmarks by atnet, and get fake image with the fake landmarks, save real images and fake images in jpeg format.
3. evaluate them by ssim and psnr, maybe others.
But, the results is different from the quantitative results in the paper. ssim is 0.73, and psnr is 21. I use the model which this code provide, but I can't confirm whether the process is right.
thank you.

**Comment by sbsws88** [comment]
> It is totally different since we need to keep identity information. The example preprocessing code can be found in demo.py.

@lelechen63 predicted landmarks using demo.py remain same for different identity images. 

> It is totally different since we need to keep identity information. The example preprocessing code can be found in demo.py.

@lelechen63 predicted landmarks using demo.py remains same for different face images and same audio. Could you please confirm if I should get different landmark predictions?

**Comment by chikiuso** [comment]
is that what you guys are looking for??
https://www.youtube.com/watch?v=wF3wOiVQclA

**Comment by lelechen63** [comment]
> > It is totally different since we need to keep identity information. The example preprocessing code can be found in demo.py.
> 
> @lelechen63 predicted landmarks using demo.py remain same for different identity images.
> 
> > It is totally different since we need to keep identity information. The example preprocessing code can be found in demo.py.
> 
> @lelechen63 predicted landmarks using demo.py remains same for different face images and same audio. Could you please confirm if I should get different landmark predictions?

You can use the preprocessing code in the demo.py. I revisit the code and find that you are right. We use same preprocessing code. That project also came from our lab. Thanks for correct this
